#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (52.66%)
# Total Accepted:    135.3K
# Total Submissions: 256.7K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        i = 0
        for char in s:
            i += ord(char)
        for char in t:
            i -= ord(char)
        return chr(-i)

# class Solution:
#     def findTheDifference(self, s: 'str', t: 'str') -> 'str':
#         from collections import Counter
#         return list((Counter(t) - Counter(s)).keys())[0]
        
